"""Initial Migration

Revision ID: eda61655a429
Revises: 
Create Date: 2026-05-26 18:42:55.426360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda61655a429'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_scores',
    sa.Column('span_id', sa.String(length=256), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Float(), nullable=False),
    sa.Column('safety', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=3000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_scores_created_at'), 'eval_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_eval_scores_id'), 'eval_scores', ['id'], unique=True)
    op.create_index(op.f('ix_eval_scores_span_id'), 'eval_scores', ['span_id'], unique=True)
    op.create_table('patients',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('triage_status', sa.Enum('PENDING', 'TRIAGED', 'IN_CONSULTATION', 'DOCUMENTED', 'REFERRED', 'DISCHARGED', name='triagestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=True)
    op.create_index(op.f('ix_patients_triage_status'), 'patients', ['triage_status'], unique=False)
    op.create_table('prompt_improvements',
    sa.Column('prompt_name', sa.String(length=200), nullable=False),
    sa.Column('previous_version_id', sa.String(length=256), nullable=True),
    sa.Column('new_version_id', sa.String(length=256), nullable=False),
    sa.Column('new_version_content', sa.String(length=10000), nullable=False),
    sa.Column('failure_patterns', sa.JSON(), nullable=False),
    sa.Column('rolling_avg_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_improvements_created_at'), 'prompt_improvements', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_improvements_id'), 'prompt_improvements', ['id'], unique=True)
    op.create_index(op.f('ix_prompt_improvements_prompt_name'), 'prompt_improvements', ['prompt_name'], unique=False)
    op.create_table('intakes',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('chief_complaint', sa.String(length=1000), nullable=False),
    sa.Column('symptom_duration_hours', sa.Integer(), nullable=False),
    sa.Column('current_medications', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('additional_history', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakes_created_at'), 'intakes', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakes_id'), 'intakes', ['id'], unique=True)
    op.create_index(op.f('ix_intakes_patient_id'), 'intakes', ['patient_id'], unique=False)
    op.create_table('triage_results',
    sa.Column('intake_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('urgency_level', sa.Integer(), nullable=False),
    sa.Column('urgency_reasoning', sa.String(length=2000), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('differentials', sa.JSON(), nullable=False),
    sa.Column('drug_flags', sa.JSON(), nullable=False),
    sa.Column('grounding_sources', sa.JSON(), nullable=False),
    sa.Column('phoenix_trace_id', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_results_created_at'), 'triage_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_triage_results_id'), 'triage_results', ['id'], unique=True)
    op.create_index(op.f('ix_triage_results_intake_id'), 'triage_results', ['intake_id'], unique=True)
    op.create_index(op.f('ix_triage_results_patient_id'), 'triage_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_triage_results_phoenix_trace_id'), 'triage_results', ['phoenix_trace_id'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('triage_result_id', sa.UUID(), nullable=True),
    sa.Column('subjective', sa.String(length=3000), nullable=False),
    sa.Column('objective', sa.String(length=3000), nullable=False),
    sa.Column('assessment', sa.String(length=3000), nullable=False),
    sa.Column('plan', sa.String(length=3000), nullable=False),
    sa.Column('doctor_signed', sa.Boolean(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_result_id'], ['triage_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_created_at'), 'clinical_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_clinical_notes_id'), 'clinical_notes', ['id'], unique=True)
    op.create_index(op.f('ix_clinical_notes_patient_id'), 'clinical_notes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_triage_result_id'), 'clinical_notes', ['triage_result_id'], unique=False)
    op.create_table('patient_briefs',
    sa.Column('triage_result_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('urgency_level', sa.Integer(), nullable=False),
    sa.Column('urgency_label', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('top_differentials', sa.JSON(), nullable=False),
    sa.Column('drug_flag_summary', sa.String(length=500), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('suggested_questions', sa.JSON(), nullable=False),
    sa.Column('improvement_notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_result_id'], ['triage_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_briefs_created_at'), 'patient_briefs', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_briefs_id'), 'patient_briefs', ['id'], unique=True)
    op.create_index(op.f('ix_patient_briefs_patient_id'), 'patient_briefs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_briefs_triage_result_id'), 'patient_briefs', ['triage_result_id'], unique=True)
    op.create_table('discharge_summaries',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('clinical_note_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.String(length=500), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.String(length=3000), nullable=False),
    sa.Column('follow_up', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinical_note_id'], ['clinical_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharge_summaries_clinical_note_id'), 'discharge_summaries', ['clinical_note_id'], unique=True)
    op.create_index(op.f('ix_discharge_summaries_created_at'), 'discharge_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_discharge_summaries_id'), 'discharge_summaries', ['id'], unique=True)
    op.create_index(op.f('ix_discharge_summaries_patient_id'), 'discharge_summaries', ['patient_id'], unique=False)
    op.create_table('referral_letters',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('clinical_note_id', sa.UUID(), nullable=False),
    sa.Column('receiving_facility', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinical_note_id'], ['clinical_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_letters_clinical_note_id'), 'referral_letters', ['clinical_note_id'], unique=True)
    op.create_index(op.f('ix_referral_letters_created_at'), 'referral_letters', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_letters_id'), 'referral_letters', ['id'], unique=True)
    op.create_index(op.f('ix_referral_letters_patient_id'), 'referral_letters', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_letters_patient_id'), table_name='referral_letters')
    op.drop_index(op.f('ix_referral_letters_id'), table_name='referral_letters')
    op.drop_index(op.f('ix_referral_letters_created_at'), table_name='referral_letters')
    op.drop_index(op.f('ix_referral_letters_clinical_note_id'), table_name='referral_letters')
    op.drop_table('referral_letters')
    op.drop_index(op.f('ix_discharge_summaries_patient_id'), table_name='discharge_summaries')
    op.drop_index(op.f('ix_discharge_summaries_id'), table_name='discharge_summaries')
    op.drop_index(op.f('ix_discharge_summaries_created_at'), table_name='discharge_summaries')
    op.drop_index(op.f('ix_discharge_summaries_clinical_note_id'), table_name='discharge_summaries')
    op.drop_table('discharge_summaries')
    op.drop_index(op.f('ix_patient_briefs_triage_result_id'), table_name='patient_briefs')
    op.drop_index(op.f('ix_patient_briefs_patient_id'), table_name='patient_briefs')
    op.drop_index(op.f('ix_patient_briefs_id'), table_name='patient_briefs')
    op.drop_index(op.f('ix_patient_briefs_created_at'), table_name='patient_briefs')
    op.drop_table('patient_briefs')
    op.drop_index(op.f('ix_clinical_notes_triage_result_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_patient_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_created_at'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_triage_results_phoenix_trace_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_patient_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_intake_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_id'), table_name='triage_results')
    op.drop_index(op.f('ix_triage_results_created_at'), table_name='triage_results')
    op.drop_table('triage_results')
    op.drop_index(op.f('ix_intakes_patient_id'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_id'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_created_at'), table_name='intakes')
    op.drop_table('intakes')
    op.drop_index(op.f('ix_prompt_improvements_prompt_name'), table_name='prompt_improvements')
    op.drop_index(op.f('ix_prompt_improvements_id'), table_name='prompt_improvements')
    op.drop_index(op.f('ix_prompt_improvements_created_at'), table_name='prompt_improvements')
    op.drop_table('prompt_improvements')
    op.drop_index(op.f('ix_patients_triage_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_eval_scores_span_id'), table_name='eval_scores')
    op.drop_index(op.f('ix_eval_scores_id'), table_name='eval_scores')
    op.drop_index(op.f('ix_eval_scores_created_at'), table_name='eval_scores')
    op.drop_table('eval_scores')
    # ### end Alembic commands ###
