[supervisord]
logfile=/home/adeyerimichael0_gmail_com/supervisord.log
user=adeyerimichael0_gmail_com
nodaemon=true
log=DEBUG

[inet_http_server]
port=*:9001
username=elle
password=super_elle

[program:gunicorn]
; command=/home/adeyerimichael0_gmail_com/fenv/bin/python /home/adeyerimichael0_gmail_com/triage_ai/backend/main.py
command=/home/adeyerimichael0_gmail_com/venv/bin/gunicorn --log-config /home/adeyerimichael0_gmail_com/triage_ai/backend/.deploy-services/logging.conf -k uvicorn.workers.UvicornWorker -w 4 --timeout 4000 --bind 0.0.0.0:8000 main:api_app
directory=/home/adeyerimichael0_gmail_com/triage_ai/backend
user=adeyerimichael0_gmail_com
stdout_logfile=/home/adeyerimichael0_gmail_com/var/log/gunicorn/output.log
stderr_logfile=/home/adeyerimichael0_gmail_com/var/log/gunicorn/error.log
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED=1

# [program:celery]
# command=/home/adeyerimichael0_gmail_com/fenv/bin/python -m celery -A src.infrastructure.celery.celery_app:celery_app worker -l info
# directory=/home/adeyerimichael0_gmail_com/triage_ai/backend
# user=adeyerimichael0_gmail_com
# numprocs=1
# stdout_logfile=/home/adeyerimichael0_gmail_com/var/log/celery/worker.log
# stderr_logfile=/home/adeyerimichael0_gmail_com/var/log/celery/worker.log
# autostart=true
# autorestart=true
# startsecs=10


# [program:celerybeat]
# command=/home/adeyerimichael0_gmail_com/fenv/bin/python -m celery -A src.infrastructure.celery.celery_app:celery_app beat -l info
# directory=/home/adeyerimichael0_gmail_com/triage_ai/backend
# user=adeyerimichael0_gmail_com
# numprocs=1
# stdout_logfile=/home/adeyerimichael0_gmail_com/var/log/celery/beat.log
# stderr_logfile=/home/adeyerimichael0_gmail_com/var/log/celery/beat.log
# autostart=true
# autorestart=true
# startsecs=10